/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuditActionBar: typeof import('./components/business/AuditActionBar.vue')['default']
    BaseButton: typeof import('./components/base/BaseButton.vue')['default']
    BaseCard: typeof import('./components/base/BaseCard.vue')['default']
    BaseEmpty: typeof import('./components/base/BaseEmpty.vue')['default']
    BaseInput: typeof import('./components/base/BaseInput.vue')['default']
    CharPrompt: typeof import('./components/business/CharPrompt.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HandwritingPad: typeof import('./components/business/HandwritingPad.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SampleUploader: typeof import('./components/business/SampleUploader.vue')['default']
    StatsCard: typeof import('./components/business/StatsCard.vue')['default']
    UserAvatar: typeof import('./components/business/UserAvatar.vue')['default']
  }
}
