#!/usr/bin/env bash
# =============================================================
#  从 .env 文件读取并设置 HandWrite-client 的所有环境变量
#  适用于 macOS / Linux（bash 3.2+ / zsh）
# =============================================================

set -e

# ---- 0. 参数解析 ----
MODE="Temporary"   # Temporary | Permanent
ENV_FILE=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        -m|--mode)    MODE="$2"; shift 2 ;;
        -f|--file)    ENV_FILE="$2"; shift 2 ;;
        -h|--help)
            echo "Usage: $0 [-m Temporary|Permanent] [-f .env-file]"
            echo ""
            echo "  -m Temporary   仅当前 shell 会话生效 (默认)"
            echo "  -m Permanent   追加到 ~/.bashrc / ~/.zshrc，重启仍生效"
            echo "  -f FILE        指定 .env 文件路径，默认 ./HandWrite-client/.env"
            exit 0
            ;;
        *) echo "[ERROR] 未知参数: $1"; exit 1 ;;
    esac
done

# ---- 1. 定位 .env ----
if [[ -z "$ENV_FILE" ]]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
    ENV_FILE="$PROJECT_DIR/.env"
fi

if [[ ! -f "$ENV_FILE" ]]; then
    echo "[ERROR] .env 文件不存在: $ENV_FILE"
    echo "        请先执行:  cp .env.example .env"
    exit 1
fi

echo "[INFO] 使用配置: $ENV_FILE"
echo "[INFO] 模式    : $MODE"
echo ""

# ---- 2. 探测当前 shell 类型（仅 Permanent 模式需要） ----
detect_rc_file() {
    if [[ -n "${ZSH_VERSION:-}" ]]; then
        echo "$HOME/.zshrc"
    elif [[ -n "${BASH_VERSION:-}" ]]; then
        # macOS bash 默认登录 shell 使用 .bash_profile，否则用 .bashrc
        if [[ "$OSTYPE" == "darwin"* ]]; then
            [[ -f "$HOME/.bash_profile" ]] && echo "$HOME/.bash_profile" || echo "$HOME/.bashrc"
        else
            echo "$HOME/.bashrc"
        fi
    else
        echo "$HOME/.profile"
    fi
}

# ---- 3. 解析 .env ----
declare -A ENV_MAP
LINE_NUM=0
SUCCESS=0
FAILED=0
TOTAL=0

while IFS= read -r line || [[ -n "$line" ]]; do
    LINE_NUM=$((LINE_NUM+1))
    # 去前后空白
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"
    # 跳过空行 / 注释
    [[ -z "$line" || "$line" == \#* ]] && continue
    # 必须包含 =
    [[ "$line" != *"="* ]] && continue

    key="${line%%=*}"
    value="${line#*=}"
    # 去 key/value 前后空白
    key="${key%"${key##*[![:space:]]}"}"
    key="${key#"${key%%[![:space:]]}"}"
    value="${value%"${value##*[![:space:]]}"}"
    value="${value#"${value%%[![:space:]]}"}"
    # 去首尾引号
    if [[ "$value" == \"*\" || "$value" == \'*\' ]]; then
        value="${value:1:-1}"
    fi

    ENV_MAP["$key"]="$value"
    TOTAL=$((TOTAL+1))
done < "$ENV_FILE"

if [[ $TOTAL -eq 0 ]]; then
    echo "[ERROR] .env 文件为空或没有有效键值对"
    exit 1
fi

echo "[INFO] 共读取 $TOTAL 个变量"
echo ""

# ---- 4. 设置环境变量 ----
RC_FILE=""
if [[ "$MODE" == "Permanent" ]]; then
    RC_FILE="$(detect_rc_file)"
    # 先清理旧条目（防止重复追加）
    TMP_MARK="# >>> HandWrite-client env >>>"
    TMP_END="# <<< HandWrite-client env <<<"
    if [[ -f "$RC_FILE" ]]; then
        if grep -q "$TMP_MARK" "$RC_FILE"; then
            # 删除旧块
            sed -i.bak "/$TMP_MARK/,/$TMP_END/d" "$RC_FILE"
        fi
    fi
fi

for key in "${!ENV_MAP[@]}"; do
    value="${ENV_MAP[$key]}"
    if [[ "$MODE" == "Temporary" ]]; then
        export "$key"="$value" && {
            echo "  [OK]   $key = $value"
            SUCCESS=$((SUCCESS+1))
        } || {
            echo "  [FAIL] $key"
            FAILED=$((FAILED+1))
        }
    else
        echo "  [OK]   $key = $value -> $RC_FILE"
        SUCCESS=$((SUCCESS+1))
    fi
done

# ---- 5. Permanent 模式：写入 rc 文件 ----
if [[ "$MODE" == "Permanent" ]]; then
    {
        echo ""
        echo "# >>> HandWrite-client env >>>"
        echo "# Generated by tools/set-env.sh on $(date '+%Y-%m-%d %H:%M:%S')"
        for key in "${!ENV_MAP[@]}"; do
            value="${ENV_MAP[$key]}"
            # 对包含特殊字符的值加引号
            if [[ "$value" =~ [[:space:]\'\"\$\\\`\(\)\&\|\;\*] ]]; then
                value="\"$value\""
            fi
            echo "export $key=$value"
        done
        echo "# <<< HandWrite-client env <<<"
    } >> "$RC_FILE"
    echo ""
    echo "        ✅ 已写入: $RC_FILE"
    echo "        ⚠️  执行 'source $RC_FILE' 或新开终端即可生效"
fi

echo ""
echo "[INFO] 设置完成: 成功=$SUCCESS  失败=$FAILED"

# ---- 6. 验证 ----
echo ""
echo "================================ 验证 ================================"
VERIFY_FAILED=0
for key in "${!ENV_MAP[@]}"; do
    expected="${ENV_MAP[$key]}"
    actual="${!key:-}"
    if [[ "$actual" == "$expected" ]]; then
        echo "  [✓] $key = $actual"
    else
        VERIFY_FAILED=$((VERIFY_FAILED+1))
        echo "  [✗] $key  期望: $expected  实际: ${actual:-<unset>}"
    fi
done

echo ""
if [[ $VERIFY_FAILED -eq 0 ]]; then
    echo "✅ 全部 $TOTAL 个变量验证通过"
    if [[ "$MODE" == "Permanent" ]]; then
        echo "   立即生效请执行:  source $RC_FILE"
    fi
else
    echo "❌ 有 $VERIFY_FAILED 个变量验证失败"
    exit 1
fi
